version: '3'

services:
  sources:
    image: postgres:latest
    container_name: olist-sources
    restart: always
    environment:
      - POSTGRES_DB=${SRC_POSTGRES_DB}
      - POSTGRES_USER=${SRC_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SRC_POSTGRES_PASSWORD}
    ports:
      - ${SRC_POSTGRES_PORT}:5432
    volumes:
      - ./helper/source_init:/docker-entrypoint-initdb.d
      - source-volume:/var/lib/postgresql/data
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SRC_POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  dwh:
    image: postgres:latest
    container_name: olist-dwh
    restart: always
    environment:
      - POSTGRES_DB=${DWH_POSTGRES_DB}
      - POSTGRES_USER=${DWH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DWH_POSTGRES_PASSWORD}
    ports:
      - ${DWH_POSTGRES_PORT}:5432
    volumes:
      - dwh_volume:/var/lib/postgresql/data
      - ./helper/dwh_init/:/docker-entrypoint-initdb.d
    depends_on:
      sources:
        condition: service_healthy

volumes:
  source-volume:
  dwh_volume: